-- Sample portfolio studio media — placeholder Unsplash photography while real
-- imagery is being captured. Idempotent: skips on duplicate file_path.

create unique index if not exists media_studio_file_path_uq on public.media_studio(file_path);

insert into public.media_studio (kind, file_path, caption_en, caption_ar, tags, sort_order, visibility) values
  ('image', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1600&auto=format&fit=crop',
    'Tower crane silhouette at golden hour.',
    'منظر للرافعة البرجية عند ساعة الذهب.',
    array['site','machinery'], 10, 'public'),
  ('image', 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?q=80&w=1600&auto=format&fit=crop',
    'Modern building exterior — completed handover.',
    'واجهة مبنى حديث — تسليم منجز.',
    array['completed','exterior'], 20, 'public'),
  ('image', 'https://images.unsplash.com/photo-1486325212027-8081e485255e?q=80&w=1200&auto=format&fit=crop',
    'Reading the structural drawings on site.',
    'مراجعة المخططات الإنشائية في الموقع.',
    array['team','design'], 30, 'public'),
  ('image', 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
    'Concrete pour during structural phase.',
    'صب الخرسانة خلال المرحلة الإنشائية.',
    array['structural','site'], 40, 'public'),
  ('image', 'https://images.unsplash.com/photo-1556909211-d5b0d6f8efe7?q=80&w=1600&auto=format&fit=crop',
    'Premium interior finishing detail.',
    'تفاصيل التشطيب الداخلي الفاخر.',
    array['interior','finishing'], 50, 'public'),
  ('image', 'https://images.unsplash.com/photo-1581094488379-6a99d39ad2c0?q=80&w=1200&auto=format&fit=crop',
    'Steel rebar grid prepared for slab pour.',
    'شبكة حديد التسليح جاهزة لصب البلاطة.',
    array['structural','rebar'], 60, 'public'),
  ('image', 'https://images.unsplash.com/photo-1508450859948-4e04fabaa4ea?q=80&w=1200&auto=format&fit=crop',
    'Bridge under construction at twilight.',
    'جسر تحت الإنشاء عند الغسق.',
    array['infrastructure','site'], 70, 'public'),
  ('image', 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=1600&auto=format&fit=crop',
    'Architectural facade detail.',
    'تفاصيل واجهة معمارية.',
    array['exterior','design'], 80, 'public'),
  ('image', 'https://images.unsplash.com/photo-1553451166-232112bda6f6?q=80&w=1200&auto=format&fit=crop',
    'Heavy machinery on industrial site.',
    'معدات ثقيلة في موقع صناعي.',
    array['industrial','machinery'], 90, 'public'),
  ('image', 'https://images.unsplash.com/photo-1510562146019-0d2eaa9b81b8?q=80&w=1600&auto=format&fit=crop',
    'Engineering team review meeting.',
    'اجتماع مراجعة لفريق الهندسة.',
    array['team','meeting'], 100, 'public'),
  ('image', 'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?q=80&w=1200&auto=format&fit=crop',
    'Modern residential tower facade.',
    'واجهة برج سكني حديث.',
    array['residential','exterior'], 110, 'public'),
  ('image', 'https://images.unsplash.com/photo-1429497419816-9ca5cfb4571a?q=80&w=1600&auto=format&fit=crop',
    'Survey crew calibrating equipment.',
    'فريق المساحة يقوم بمعايرة المعدات.',
    array['team','survey'], 120, 'public')
on conflict (file_path) do nothing;
