-- Sample open careers — 6 bilingual roles spanning the four sectors plus corporate.
-- Idempotent on slug. closes_at set ~60 days out from migration date (2026-05-04).

insert into public.careers
  (slug, title_en, title_ar, department_en, department_ar,
   location_en, location_ar, type_en, type_ar,
   description_en, description_ar, requirements_en, requirements_ar,
   status, closes_at)
values
  ('senior-structural-engineer',
   'Senior Structural Engineer',
   'مهندس إنشائي أول',
   'Engineering',
   'الهندسة',
   'Riyadh, KSA',
   'الرياض، المملكة العربية السعودية',
   'Full-time',
   'دوام كامل',
   'Lead the structural design and review for high-rise residential and mixed-use projects. Coordinate with architectural, MEP, and project-management teams from concept through handover. Sign and seal drawings under our Saudi Council of Engineers firm accreditation.',
   'قيادة التصميم الإنشائي ومراجعته لمشاريع الأبراج السكنية ومتعددة الاستخدامات. التنسيق مع فرق العمارة والكهروميكانيكا وإدارة المشاريع من الفكرة حتى التسليم. اعتماد المخططات تحت ترخيص هيئة المهندسين السعوديين.',
   '8+ years of structural design experience in the Saudi market. SCE membership. Proficiency in ETABS, SAFE, and Revit Structure. Working knowledge of the Saudi Building Code. Bilingual (Arabic / English).',
   'خبرة 8+ سنوات في التصميم الإنشائي بالسوق السعودي. عضوية هيئة المهندسين السعوديين. إتقان ETABS و SAFE و Revit Structure. إلمام بكود البناء السعودي. ثنائي اللغة (عربي / إنجليزي).',
   'open', '2026-07-04'),

  ('project-manager-fitout',
   'Project Manager — Interior Fit-out',
   'مدير مشروع — التشطيبات الداخلية',
   'Interior Finishing',
   'التشطيبات الداخلية',
   'Jeddah, KSA',
   'جدة، المملكة العربية السعودية',
   'Full-time',
   'دوام كامل',
   'Run premium fit-out projects for executive offices, hospitality, and high-end residential — from joinery shop drawings through snagging and handover. Manage subcontractors, budgets, and program against contractual milestones.',
   'إدارة مشاريع التشطيبات الفاخرة للمكاتب التنفيذية والضيافة والوحدات السكنية الراقية — من رسومات النجارة وحتى التسليم النهائي. إدارة المقاولين من الباطن والميزانيات والبرامج وفق المعالم التعاقدية.',
   '6+ years of fit-out PM experience in KSA or GCC. Strong joinery and finishes background. PMP or equivalent. Comfortable with Primavera P6 and MS Project. Bilingual.',
   'خبرة 6+ سنوات في إدارة مشاريع التشطيبات بالمملكة أو دول الخليج. خلفية قوية في النجارة والتشطيبات. شهادة PMP أو ما يعادلها. إجادة Primavera P6 و MS Project. ثنائي اللغة.',
   'open', '2026-07-04'),

  ('site-engineer-concrete',
   'Site Engineer — Structural & Concrete',
   'مهندس موقع — إنشائي وخرساني',
   'Structural Works',
   'الأعمال الإنشائية',
   'Riyadh, KSA',
   'الرياض، المملكة العربية السعودية',
   'Full-time',
   'دوام كامل',
   'On-site execution of foundations, frames, and reinforced-concrete works. Daily quality checks, pour planning, and progress reporting to the project manager. Coordinate with the consultant for inspections and approvals.',
   'التنفيذ الميداني للأساسات والهياكل وأعمال الخرسانة المسلحة. فحوصات الجودة اليومية وتخطيط الصبّ ورفع التقارير لمدير المشروع. التنسيق مع الاستشاري للتفتيش والاعتمادات.',
   '3–5 years of structural site experience. BSc Civil Engineering. SCE membership. Familiar with PLAXIS or similar geotechnical software. Arabic native, English working level.',
   'خبرة 3–5 سنوات في الإشراف الإنشائي. بكالوريوس هندسة مدنية. عضوية هيئة المهندسين السعوديين. إلمام بـ PLAXIS أو برنامج جيوتقني مماثل. لغة عربية أصلية وإنجليزية للعمل.',
   'open', '2026-07-04'),

  ('quantity-surveyor',
   'Quantity Surveyor',
   'مساح كميات',
   'Engineering',
   'الهندسة',
   'Riyadh, KSA',
   'الرياض، المملكة العربية السعودية',
   'Full-time',
   'دوام كامل',
   'Prepare BOQs, take-offs, and tender packages across our portfolio. Negotiate variations and progress claims with consultants and clients. Maintain cost reports and forecasts for active projects.',
   'إعداد جداول الكميات والاستخراجات وحزم العطاءات لمحفظتنا. التفاوض على المتغيرات ومطالبات التقدم مع الاستشاريين والعملاء. متابعة تقارير التكاليف والتوقعات للمشاريع النشطة.',
   '4+ years QS experience in KSA construction. CCS Candy or CostX proficiency. Strong knowledge of FIDIC and Saudi public-works contract forms. Bilingual.',
   'خبرة 4+ سنوات كمساح كميات في قطاع الإنشاءات بالمملكة. إتقان CCS Candy أو CostX. معرفة قوية بعقود فيديك وعقود الأشغال العامة السعودية. ثنائي اللغة.',
   'open', '2026-07-04'),

  ('procurement-officer',
   'Procurement Officer',
   'موظف مشتريات',
   'Trade & Procurement',
   'التجارة والمشتريات',
   'Riyadh, KSA',
   'الرياض، المملكة العربية السعودية',
   'Full-time',
   'دوام كامل',
   'Source construction materials, MEP equipment, and finishing items from local and international suppliers. Negotiate pricing, lead times, and payment terms. Maintain the approved-vendor list and trace purchase orders end-to-end.',
   'توريد مواد البناء ومعدات الكهروميكانيكا ومواد التشطيب من موردين محليين ودوليين. التفاوض على الأسعار وأوقات التسليم وشروط السداد. متابعة قائمة الموردين المعتمدين وتتبع أوامر الشراء.',
   '3+ years procurement experience in construction or industrial sectors. Proven supplier network in the Kingdom. ERP exposure (SAP, Oracle, or similar). Bilingual.',
   'خبرة 3+ سنوات في المشتريات في قطاعَي الإنشاءات أو الصناعة. شبكة موردين موثوقة داخل المملكة. خبرة في أنظمة ERP (SAP أو Oracle أو ما يماثلها). ثنائي اللغة.',
   'open', '2026-07-04'),

  ('hr-business-partner',
   'HR Business Partner',
   'شريك أعمال موارد بشرية',
   'Corporate',
   'الإدارة العامة',
   'Riyadh, KSA',
   'الرياض، المملكة العربية السعودية',
   'Full-time',
   'دوام كامل',
   'Partner with sector leads on workforce planning, hiring, performance, and Saudization compliance. Run end-to-end recruitment for engineering and corporate roles. Own GOSI, Mudad, and Qiwa workflows.',
   'العمل مع قادة القطاعات في تخطيط القوى العاملة والتوظيف وإدارة الأداء والامتثال للسعودة. إدارة دورة التوظيف الكاملة للوظائف الهندسية والإدارية. الإشراف على إجراءات التأمينات ومدد وقوى.',
   '5+ years HRBP experience in KSA. Solid grasp of Saudi labor law, GOSI, Mudad, and Qiwa platforms. CIPD or SHRM certification preferred. Bilingual.',
   'خبرة 5+ سنوات كشريك أعمال موارد بشرية في المملكة. إلمام بنظام العمل السعودي ومنصات التأمينات ومدد وقوى. شهادة CIPD أو SHRM يُفضَّل وجودها. ثنائي اللغة.',
   'open', '2026-07-04')
on conflict (slug) do nothing;
